services:
  postgres_db:
    image: postgres:16-alpine
    container_name: postgres_container
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: auth_db
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    container_name: keycloak_container
    restart: unless-stopped
    ports:
      - 8088:8080
      - 8081:8443
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres_db:5432/auth_db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /home/kakan/Workspace/keycloak-demo/certs:/etc/ssl/certs:ro
    command: [ 'start',
               '--https-certificate-file=/etc/ssl/certs/keycloak.crt.pem',
               '--https-certificate-key-file=/etc/ssl/certs/keycloak.key.pem',
               '--hostname=localhost'
    ]
volumes:
  postgres:
  pgadmin: